"""fixed error with language characters. Back to 10 chars

Revision ID: 107ee04d39d7
Revises: 28e36aff3184
Create Date: 2024-02-28 10:45:02.523285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '107ee04d39d7'
down_revision = '28e36aff3184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
