"""Latitude, Longtitude Update

Revision ID: 999dd6afb3fa
Revises: 58bc3dcca1be
Create Date: 2024-04-05 21:35:45.015184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999dd6afb3fa'
down_revision = '58bc3dcca1be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
